bind=10.117.57.173:9999
dbname=moredoc
sqluser=root
nginx=10.117.57.173:9999
sqlhost=10.117.57.173
sqlport=3316
sqlpassword=mbYJozX1OBI
baseConfigPath=/home/kongs/go/src/code/moredoc
gspRegions=defaultRegion
accessKey=LeBnhmXCSrYemEjv
secretKey=CGHdmxXRjIvjaUsZ
gspAddr=10.117.57.162:23471



